local state = require("provenance.recorder.state")
local status = require("provenance.recorder.status")

describe("status", function()
  after_each(function()
    status.detach()
  end)

  it("no state attached: segment() is empty", function()
    assert.equals("", status.segment())
  end)

  it("attach an inactive state: segment() is empty", function()
    local s = state.new()
    status.attach(s)
    assert.equals("", status.segment())
  end)

  it("attach an active state: segment() is the recording indicator", function()
    local s = state.new()
    status.attach(s)
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    local segment = status.segment()
    assert.is_not.equals("", segment)
    assert.is_not_nil(string.find(segment, "recording"))
    assert.equals("● Provenance: recording", segment)
  end)

  it("after deactivate() with state still attached: segment() is empty", function()
    local s = state.new()
    status.attach(s)
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    s.deactivate()
    assert.equals("", status.segment())
  end)

  it("after status.detach(): segment() is empty", function()
    local s = state.new()
    status.attach(s)
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    status.detach()
    assert.equals("", status.segment())
  end)
end)
