local state = require("provenance.recorder.state")

describe("RecorderState", function()
  it("fresh state is inactive", function()
    local s = state.new()
    assert.is_false(s.is_active())
  end)

  it("fresh state get() returns active=false with nil workspace and manifest", function()
    local s = state.new()
    local data = s.get()
    assert.equals(false, data.active)
    assert.is_nil(data.workspace)
    assert.is_nil(data.manifest)
  end)

  it("after activate() is_active() returns true", function()
    local s = state.new()
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    assert.is_true(s.is_active())
  end)

  it("after activate() get() returns the workspace and manifest", function()
    local s = state.new()
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    local data = s.get()
    assert.equals(true, data.active)
    assert.equals("/tmp/ws", data.workspace)
    assert.equals("hw3", data.manifest.assignment_id)
  end)

  it("after deactivate() is_active() returns false", function()
    local s = state.new()
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    s.deactivate()
    assert.is_false(s.is_active())
  end)

  it("after deactivate() get() returns active=false with nil workspace and manifest", function()
    local s = state.new()
    s.activate({ workspace = "/tmp/ws", manifest = { assignment_id = "hw3" } })
    s.deactivate()
    local data = s.get()
    assert.equals(false, data.active)
    assert.is_nil(data.workspace)
    assert.is_nil(data.manifest)
  end)

  it("two independent instances do not share state", function()
    local s1 = state.new()
    local s2 = state.new()
    s1.activate({ workspace = "/tmp/ws1", manifest = { assignment_id = "hw1" } })
    assert.is_true(s1.is_active())
    assert.is_false(s2.is_active())
    assert.is_nil(s2.get().workspace)
  end)
end)
